### ISSUE TITLE
Gene level expression

### ISSUE THREAD

**Issue by johnmu** [alyssafrazee/polyester#17]
I may have missed this in the documentation. But, in the output is it possible to find the simulated gene level expression given that I input a GTF of transcripts and associated fold changes for those transcripts?

If this is not possible, I guess this only way is to input a GTF of genes instead?

Thanks!

**Comment by alyssafrazee** [comment]
Do you mean you want the simulated gene-level fold changes? I think you could calculate it based on the input baseline expression and fold change for all the transcripts in the gene. Alternatively, if you wanted to specifically set the gene-level fold changes without inputting a GTF of genes, you could set the fold change to be the same thing for all transcripts in the gene. I wouldn't recommend using a GTF of genes, as the RNA-sequencing process operates at transcript-level (so the simulated data would likely be less noisy than real RNA-seq data).
