### ISSUE TITLE
output:  .fasta.gz

### ISSUE THREAD

**Issue by FabianGrammes** [alyssafrazee/polyester#22]
Hi
I'm testing your package for some bigger simulation. Would it be possible to get gziped .fasta files instead of .fasta files from `simulate_experiment`? 

Cheers F

**Comment by alyssafrazee** [comment]
Thanks for the feature request! I'll check on the feasibility and get back to you.

**Comment by alyssafrazee** [comment]
This is now supported in version 1.5.1 (via 216dd52310dd0bd1b170369b53da979b87407f4b and 9e308a9f53dec7ff5b8850e1fe6c2d0d89320b12).
