### ISSUE TITLE
Distribution of reads

### ISSUE THREAD

**Issue by shrukane** [alyssafrazee/polyester#27]
Is there any way we can plot the distribution of reads in the simulation ?

**Comment by JMF47** [comment]
Hey Shruti, there is currently no method for that. But I will write one in and incorporate it into the code. This is a pretty useful feature. Would you just like to have the number of reads that cover each base of the reference sequences that you submitted for simulation from?

**Comment by shrukane** [comment]
That would be great ! Thank you.

**Comment by shrukane** [comment]
Hi, any updates ?

**Comment by JMF47** [comment]
Hey! Sorry I was on vacation, but I have written the code this morning to the devel version to polyester. Please try it out and see if it does what you want it to do. To start polyester in devel please do:

```
library(devtools)
dev_mode()
install_github("alyssafrazee/polyester")
library(polyester)
```
Then you can run the simulation as you normally do, except modify the `simulate_experiment` command slightly by inserting the argument
``` simulate_experiment(..., reportCoverage=T)```

This will create a 'sample_coverages.rda` file in the same directory where you have generated the reads.
In this file, is stored a list of matrices. The names of each entry in the list corresponds to the transcript from which reads are generated. Each entry in the list is a matrix for that transcript. The i-th column of the matrix corresponds to i-th dataset generated from polyester, while the j-th row corresponds to the number of reads that will map to that position along that transcript (theoretical prefect coverage before errors are introduced during simulation).

Let me know if you need any more help!

**Comment by shrukane** [comment]
hi, sorry for the late reply. when I run my code I get the following error
Error in save(coverage_matrices, file = paste0(outdir, "/sample_coverages.rda")) : 
  object ‘coverage_matrices’ not found

**Comment by shrukane** [comment]
Hi, I know this is a closed call but I have one more question. Is this method incorporated in the latest version of polyester ? I've been working on the latest version and i could not find the sample_coverages.rda file.
-Shruti
