### ISSUE TITLE
basemeans: number of items to replace is not a multiple of replacement length

### ISSUE THREAD

**Issue by mikelove** [alyssafrazee/polyester#42]
The latest commit (also pushed to Bioc devel) produces an error when `num_reps` has length 2, and `fold_changes` is a matrix of dimensions: #transcripts x 2. This is the dimension of `fold_changes` that is specified by the docs:

https://github.com/alyssafrazee/polyester/blob/master/R/simulate_experiment.R#L139-L142

Here's the line that's the problem:

```
basemeans[,2] = fold_changes * basemeans[,1]
```

https://github.com/alyssafrazee/polyester/blob/master/R/simulate_experiment.R#L376

Bioc devel build report:

http://bioconductor.org/checkResults/devel/bioc-LATEST/polyester/malbec1-buildsrc.html

(I see you're changing things to support multi-group DE which is great.)

If you're already aware of what's happening feel free to close this issue. If you would like an example and more information, just ping me.

**Comment by JMF47** [comment]
Thanks for the headsup, made patching the error much much much easier!

**Comment by alessandraalves** [comment]
Hello. I am having this exact same problem, and I need desperately to fix it. However I haven't been able to do it so far, can you help me on this one, please? The bioc devel report is out.

**Comment by manuelsmendoza** [comment]
is it still bugged?

**Comment by luguodexxx** [comment]
is it still bugged?
