### ISSUE TITLE
Simulate Reads Without Experiment?

### ISSUE THREAD

**Issue by nmshahir** [alyssafrazee/polyester#78]
Amazing tool! Forgive me for the very simplistic question but is there any way to simulate an experiment without fold changes?

**Comment by alyssafrazee** [comment]
You can set all fold changes = 1!

**Comment by nmshahir** [comment]
So I tried that and get
`Error in simulate_experiment("chr22_small.fa", readlen = 90, meanmodel = TRUE,  : 
  object 'basemeans' not found `

this is the code I'm running using the data provided in polyester
`simulate_experiment('chr22_small.fa',readlen=90,meanmodel=TRUE,
                    num_reps=1, fold_changes=1, outdir='simulated_reads') `

**Comment by nmshahir** [comment]
Update: figured it out! I needed to update R.
