### ISSUE TITLE
Snakemake workflow of Polyester

### ISSUE THREAD

**Issue by NaotoKubota** [alyssafrazee/polyester#84]
Hi,

Thank you for creating this amazing tool! It has been incredibly helpful for my simulation studies of alternative RNA splicing.

I developed a Snakemake workflow for Polyester, called [SnakePolyester](https://github.com/NaotoKubota/SnakePolyester). This workflow facilitates the simulation of RNA-seq data across multiple scenarios. It automates the generation of FASTA files, converts them to FASTQ format, and maps them to the reference genome using STAR.

However, I was unable to find the license file for Polyester. Could you please provide information on its licensing terms? It is crucial for ensuring that my use of Polyester complies with the appropriate legal guidelines.

Thank you once again for your valuable tool and your assistance.

Best regards,

**Comment by alyssafrazee** [comment]
The license is [Artistic 2.0](https://opensource.org/license/artistic-2-0):
* https://github.com/alyssafrazee/polyester/blob/master/DESCRIPTION#L6
* https://www.bioconductor.org/packages/release/bioc/html/polyester.html

Sounds like a cool project!
